<?php

namespace AppBundle\Repository;

/**
 * AtelierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class AtelierRepository
 * @package AppBundle\Repository
 */
class AtelierRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllValidOverOneMonth()
    {
        return $this
            ->getEntityManager()
            ->createQuery('SELECT e '
                . 'FROM AppBundle:Atelier e '
                . 'WHERE e.annule = :annule '
                . 'AND e.affiche = :affiche '
                . 'AND e.date >= :date '
                . 'ORDER BY e.date DESC')
            ->setParameters([
                'annule'  => false,
                'affiche' => true,
                'date'    => date("Y-m-d",strtotime("-1 month"))
            ])
            ->getResult();
    }
}
