<?php

namespace AppBundle\Repository;

/**
 * AtelierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class AtelierRepository
 * @package AppBundle\Repository
 */
class AtelierRepository extends \Doctrine\ORM\EntityRepository
{
}
