<?php

namespace AppBundle\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class BlogRepository
 * @package AppBundle\Repository
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
}
