<?php

namespace AppBundle\Repository;

/**
 * ContenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class ContenuRepository
 * @package AppBundle\Repository
 */
class ContenuRepository extends \Doctrine\ORM\EntityRepository
{
}
