<?php

namespace AppBundle\Repository;

/**
 * CourDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class CourDetailRepository
 * @package AppBundle\Repository
 */
class CourDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
