<?php

namespace AppBundle\Repository;

/**
 * CourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class CourRepository
 * @package AppBundle\Repository
 */
class CourRepository extends \Doctrine\ORM\EntityRepository
{
}
