<?php

namespace AppBundle\Repository;

/**
 * DateCalendrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class DateCalendrierRepository
 * @package AppBundle\Repository
 */
class DateCalendrierRepository extends \Doctrine\ORM\EntityRepository
{
}
