<?php

namespace AppBundle\Repository;

/**
 * DemandeAccesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeAccesRepository extends \Doctrine\ORM\EntityRepository
{

}
