<?php

namespace AppBundle\Repository;

/**
 * DemandeNewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeNewsletterRepository extends \Doctrine\ORM\EntityRepository
{

}
