<?php

namespace AppBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class EvenementRepository
 * @package AppBundle\Repository
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
}
