<?php

namespace AppBundle\Repository;

/**
 * InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class InscriptionRepository
 * @package AppBundle\Repository
 */
class InscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
