<?php

namespace AppBundle\Repository;

/**
 * ParametreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class ParametreRepository
 * @package AppBundle\Repository
 */
class ParametreRepository extends \Doctrine\ORM\EntityRepository
{
}
