<?php

namespace AppBundle\Repository;

/**
 * RubriqueRepository
 *
 * This blass was generated by the Doctrine ORM. Add your own bustom
 * repository methods below.
 */
class RubriqueRepository extends \Doctrine\ORM\EntityRepository
{
   
}
