<?php

namespace AppBundle\Repository;

/**
 * SortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class SortieRepository
 * @package AppBundle\Repository
 */
class SortieRepository extends \Doctrine\ORM\EntityRepository
{
   
}
