<?php

namespace AppBundle\Repository;

/**
 * StatistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatistiqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function sumByMonth($monthNumber, $thisYear = true)
    {
        $year = (int)(new \DateTime())->format('Y');
        if (!$thisYear) {
            $year--;
        }
        $date = $year.'-'.($monthNumber<10?'0'.$monthNumber:$monthNumber);
        $startDate = $date.'-01';
        $endDate   = $date.'-31';

        return $this->createQueryBuilder('s')
            ->andWhere('s.timestampCreation BETWEEN :startDate AND :endDate ')
            ->setParameters(['startDate' => $startDate, 'endDate' => $endDate])
            ->select('SUM(s.occurence) as occurenceMensuel')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
