<?php

namespace AppBundle\Repository;

/**
 * TypeRubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class TypeRubriqueRepository
 * @package AppBundle\Repository
 */
class TypeRubriqueRepository extends \Doctrine\ORM\EntityRepository
{
}
