<?php

namespace AppBundle\Repository;

/**
 * UtilisateurLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurLogRepository extends \Doctrine\ORM\EntityRepository
{
    
}
