imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata_admin.yml }
    - { resource: sonata_media.yml }
    - { resource: sonata_block.yml }
    - { resource: sonata_user.yml }
    - { resource: sonata_intl.yml }
    - { resource: sonata_classification.yml }
    - { resource: sonata_news.yml }
    - { resource: sonata_formatter.yml }
    - { resource: fos_user.yml }
    - { resource: knp_snappy.yml }
    - { resource: ivory_ck_editor.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    web_path: "%kernel.root_dir%/../web"

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path: "/var/lib/php/session/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    form_themes:
        - "form_templates/rouenjapon.html.twig"
        - 'SonataCoreBundle:Form:datepicker.html.twig'
        - 'SonataMediaBundle:Form:media_widgets.html.twig'
        - ':OhGoogleMapFormTypeBundle/Form:fields.html.twig'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: app.error_controller:showAction
    globals:
        web_path: '%web_path%'
        google_recaptcha_public_token: '%google_recaptcha_public_token%'
        google_analytics_ua: '%google_analytics_ua%'
        trello_link: '%trello_link%'
        planneur_link: '%planneur_link%'
        num_version: '%num_version%'
        gmaps_apikey: '%gmaps_apikey%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        # added for sonata user
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    #ApplicationSonataUserBundle: AppBundle\Entity\Utilisateur
                    SonataUserBundle: ~
                    FOSUserBundle: ~
                    ApplicationSonataMediaBundle: ~
                    ApplicationSonataNewsBundle: ~
                    SonataMediaBundle: ~
                    SonataNewsBundle: ~


stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations


# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    encryption: '%mailer_encryption%'
    auth_mode: '%mailer_auth_mode%'
    spool: { type: memory }

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    bundles: [ 'OhGoogleMapFormTypeBundle' ]

oh_google_map_form_type:
    api_key: "%gmaps_apikey%"