imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 35
        console:
            type: console
        import:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%/import.log'
            level: debug
            max_files: 35
            facility: user


framework:
    session:
        save_path: "/var/www/sessions/%kernel.environment%"

# Assetic Configuration
assetic:
    debug:          false
    use_controller: false
    bundles:
        - AppBundle