fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\Utilisateur
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    group:
        group_class: AppBundle\Entity\UtilisateurDroits
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

jms_translation:
    source_language: 'fr'
    locales: ['fr']
    configs:
        app:
            dirs: ["%kernel.root_dir%", "%kernel.root_dir%/../src"]
            output_dir: "%kernel.root_dir%/Resources/translations"
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php", "*~"]
            excluded_dirs: [cache, data, logs, Tests]
            output_format: "yml"