knp_snappy:
    pdf:
        enabled:    true
        binary:     "%kernel.root_dir%/../bin/wkhtmltox/bin/wkhtmltopdf"
        options:    []
    image:
        enabled:    true
        binary:     "%kernel.root_dir%/../bin/wkhtmltox/bin/wkhtmltoimage"
        options:    []
    temporary_folder: "%kernel.cache_dir%/snappy"