app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /gyosei

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /gyosei

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /gyosei

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /gyosei/resetting

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
