app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /gyosei

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /gyosei

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /gyosei

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /gyosei/resetting

sonata_user_impersonating:
    path:  /gyosei/dashboard
    defaults: { _controller: SonataPageBundle:Page:catchAll }

fos_user_security_check:
    path: '/login_check'
    defaults: { _controller: FOSUserBundle:Security:check }
    methods:  [POST]

fos_user_security_logout:
    path: '/logout'
    defaults: { _controller: FOSUserBundle:Security:logout }
    methods:  [GET, POST]

fos_user_security_login:
    path: '/'

fos_user_resetting:
    resource: '@FOSUserBundle/Resources/config/routing/resetting.xml'
    prefix: /resetting

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /gyosei/media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /gyosei/media
