# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_EDITOR:
            - ROLE_APP_ADMIN_ACTUALITES_EDITOR
            - ROLE_APP_ADMIN_ATELIERS_EDITOR
            - ROLE_APP_ADMIN_BLOG_EDITOR
            - ROLE_APP_ADMIN_SORTIES_EDITOR
            - ROLE_APP_ADMIN_KOURYUKAI_EDITOR
            - ROLE_APP_ADMIN_CONGES_EDITOR
            - ROLE_APP_ADMIN_COURS_EDITOR
            - ROLE_APP_ADMIN_COURS_DETAILS_EDITOR
            - ROLE_APP_ADMIN_COURS_DATES_EDITOR
            - ROLE_APP_ADMIN_COURS_REPORTS_EDITOR
            - ROLE_APP_ADMIN_EVENEMENTS_EDITOR
            - ROLE_APP_ADMIN_PARAMETRES_EDITOR
            - ROLE_APP_ADMIN_PARTENAIRES_EDITOR
            - ROLE_APP_ADMIN_NEWSLETTER_EDITOR
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_EDITOR
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_EDITOR
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_EDITOR
            - ROLE_APP_ADMIN_TAGS_EDITOR
            - ROLE_APP_ADMIN_IMPORTS_EDITOR
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SONATA_USER_ADMIN_USER_ADMIN
            - ROLE_SONATA_USER_ADMIN_GROUP_ADMIN
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_ADMIN 
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_ADMIN
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_ADMIN
            - ROLE_APP_ADMIN_ACTUALITES_ADMIN
            - ROLE_APP_ADMIN_BLOG_ADMIN
            - ROLE_APP_ADMIN_ATELIERS_ADMIN
            - ROLE_APP_ADMIN_SORTIES_ADMIN
            - ROLE_APP_ADMIN_KOURYUKAI_ADMIN
            - ROLE_APP_ADMIN_COURS_ADMIN
            - ROLE_APP_ADMIN_CONGES_ADMIN
            - ROLE_APP_ADMIN_COURS_DETAILS_ADMIN
            - ROLE_APP_ADMIN_COURS_DATES_ADMIN
            - ROLE_APP_ADMIN_COURS_REPORTS_ADMIN
            - ROLE_APP_ADMIN_EVENEMENTS_ADMIN
            - ROLE_APP_ADMIN_PARAMETRES_ADMIN
            - ROLE_APP_ADMIN_PARTENAIRES_ADMIN
            - ROLE_APP_ADMIN_NEWSLETTER_ADMIN
            - ROLE_APP_ADMIN_TAGS_ADMIN
            - ROLE_APP_ADMIN_IMPORTS_ADMIN
            - ROLE_SONATA_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]        

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    acl:
        connection: default

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:            /gyosei/(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /gyosei/login
                use_forward:    false
                check_path:     /gyosei/login_check
                failure_path:   /gyosei/login
                default_target_path: /gyosei/dashboard
            logout:
                path:           /gyosei/logout
                target:         /gyosei/login
            anonymous:          true
            switch_user: true

        main:
            pattern:             /(.*)
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                remember_me: true
                login_path:  /
                check_path:  /login_check
                success_handler: authentication_handler
                failure_handler: authentication_handler
                default_target_path: /mon-espace
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                path:     /
            logout:
                path:        /logout
                target:      /
            anonymous:    true

    access_control:
        # Admin login page needs to be accessed without credential
        - { path: ^/gyosei/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/gyosei/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/gyosei/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/gyosei/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/gyosei/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mon-espace, role: IS_AUTHENTICATED_FULLY }
