# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    security.acl.permission.map:
        class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

    twig_asset_version_extension:
        class: AppBundle\Twig\AssetVersionExtension
        arguments: ["%kernel.root_dir%"]
        tags:
            - { name: twig.extension }

    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

    app.admin.block.stats:
        class: AppBundle\Service\StatBlockService
        arguments: ["app.admin.block.stats", "@templating", "@doctrine.orm.entity_manager", "@sonata.admin.pool"]
        tags:
            - { name: sonata.block }

    app.admin.evenements:
        class: AppBundle\Admin\EvenementAdmin
        arguments: [~, AppBundle\Entity\Evenement, AppBundle:Evenement]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Evenements }

    app.admin.actualites:
        class: AppBundle\Admin\ActualiteAdmin
        arguments: [~, AppBundle\Entity\Actualite, AppBundle:Actualite]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Actualites }

    app.admin.blog:
        class: AppBundle\Admin\BlogAdmin
        arguments: [~, AppBundle\Entity\Blog, AppBundle:Blog]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Blog }

    app.admin.tags:
        class: AppBundle\Admin\TagAdmin
        arguments: [~, AppBundle\Entity\Tag, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Tags }


    app.admin.partenaires:
        class: AppBundle\Admin\PartenaireAdmin
        arguments: [~, AppBundle\Entity\Partenaire, AppBundle:Partenaire]
        tags:

            - { name: sonata.admin, manager_type: orm, group: admin, label: Partenaire }

    app.admin.newsletter:
        class: AppBundle\Admin\DemandeNewsletterAdmin
        arguments: [~, AppBundle\Entity\DemandeNewsletter, AppBundle:DemandeNewsletter]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: DemandeNewsletter }

    app.admin.sorties:
        class: AppBundle\Admin\SortieAdmin
        arguments: [~, AppBundle\Entity\Sortie, AppBundle:Sortie]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Sorties }

    app.admin.kouryukai:
        class: AppBundle\Admin\KouryukaiAdmin
        arguments: [~, AppBundle\Entity\Kouryukai, AppBundle:Kouryukai]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Kouryukai }

    app.admin.ateliers:
        class: AppBundle\Admin\AtelierAdmin
        arguments: [~, AppBundle\Entity\Atelier, AppBundle:Atelier]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Ateliers }

    app.admin.parametres:
        class: AppBundle\Admin\ParametreAdmin
        arguments: [~, AppBundle\Entity\Parametre, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Parametres }

    app.admin.cours:
        class: AppBundle\Admin\CourAdmin
        arguments: [~, AppBundle\Entity\Cour, AppBundle:Cour]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Cours }

    app.admin.conges:
        class: AppBundle\Admin\CongeAdmin
        arguments: [~, AppBundle\Entity\Conge, AppBundle:Conge]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Congés }

    app.admin.cours_details:
        class: AppBundle\Admin\CourDetailAdmin
        arguments: [~, AppBundle\Entity\CourDetail, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: CoursDetail }

    app.admin.cours_dates:
        class: AppBundle\Admin\CourDateAdmin
        arguments: [~, AppBundle\Entity\CourDate, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: CoursDate }

    app.admin.cours_reports:
        class: AppBundle\Admin\CourReportAdmin
        arguments: [~, AppBundle\Entity\CourReport, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: CoursReport }

    app.error_controller:
        class: AppBundle\Controller\Front\ErrorController
        arguments: ['@twig', '%kernel.debug%']

    app.twig_helper:
        class: AppBundle\Twig\TwigHelpers
        arguments: ["@doctrine.orm.entity_manager", "@sonata.media.provider.image"]
        tags:
            - { name: twig.extension }
    app.admin.block.timeline:
        class: AppBundle\Service\TimeLineBlockService
        arguments: ["app.admin.block.timeline", "@templating", "@doctrine.orm.entity_manager", "@sonata.admin.pool"]
        tags:
            - { name: sonata.block }

    app.admin.block.statistique:
        class: AppBundle\Service\StatistiqueBlockService
        arguments: ["app.admin.block.statistique", "@templating", "@doctrine.orm.entity_manager", "@sonata.admin.pool"]
        tags:
            - { name: sonata.block }

    app.event_listener.user_entity:
        class: AppBundle\EventListener\UtilisateurLogListener
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    app.event_listener.statistique:
        class: AppBundle\EventListener\StatistiqueListener
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    app.google_calendar:
        class: AppBundle\Service\GoogleCalendar
        arguments: ["%google_calendar_application_name%", "%kernel.root_dir%/../%google_calendar_client_secret%", "%kernel.root_dir%/../%google_calendar_credential_path%", "@monolog.logger"]

    app.generate_calendar:
        class: AppBundle\Service\GenerateCalendar
        arguments: ["@doctrine.orm.entity_manager", "@app.google_calendar"]