# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.admin.block.stats:
        class: AppBundle\Service\StatBlockService
        arguments: ["app.admin.block.stats", "@templating", "@doctrine.orm.entity_manager", "@sonata.admin.pool"]
        tags:
            - { name: sonata.block }