sonata_admin:
    title: 'Rouen Japon Administration'
    title_logo: medias/favicons/favicon-32x32.png
    options:
        html5_validate: true
        # Auto order groups and admins by label or id
        sort_admins: false
        confirm_exit: true # prevent data corruption when multiple users edit an object at the same tim
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]

        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]

        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
        layout: :AdminCustom:/template/standard_layout.html.twig
        edit:   :AdminCustom:/template/edit.html.twig
        user_block: :AdminCustom:/template/user_block.html.twig

    dashboard:
        groups:
            app.admin.group.principal.evenements:
                on_top: true
                label: "Evenements"
                icon: '<i class="fa fa-calendar"></i>'
                roles: [ROLE_APP_ADMIN_EVENEMENTS_GUEST, ROLE_APP_ADMIN_EVENEMENTS_STAFF, ROLE_APP_ADMIN_EVENEMENTS_EDITOR, ROLE_APP_ADMIN_EVENEMENTS_ADMIN]
                items:
                    - app.admin.evenements
            app.admin.group.principal.actualites:
                on_top: true
                label: "Actualites"
                icon: '<i class="fa fa-newspaper-o"></i>'
                roles: [ROLE_APP_ADMIN_ACTUALITES_GUEST, ROLE_APP_ADMIN_ACTUALITES_STAFF, ROLE_APP_ADMIN_ACTUALITES_EDITOR, ROLE_APP_ADMIN_ACTUALITES_ADMIN]
                items:
                    - app.admin.actualites
            app.admin.group.principal.kouryukai:
                on_top: true
                label: "Kouryukai"
                icon: '<i class="fa fa-clock-o"></i>'
                roles: [ROLE_APP_ADMIN_KOURYUKAI_GUEST, ROLE_APP_ADMIN_KOURYUKAI_STAFF, ROLE_APP_ADMIN_KOURYUKAI_EDITOR, ROLE_APP_ADMIN_KOURYUKAI_ADMIN]
                items:
                    - app.admin.kouryukai
            app.admin.group.principal.sorties:
                on_top: true
                label: "Sorties"
                icon: '<i class="fa fa-car"></i>'
                roles: [ROLE_APP_ADMIN_SORTIES_GUEST, ROLE_APP_ADMIN_SORTIES_STAFF, ROLE_APP_ADMIN_SORTIES_EDITOR, ROLE_APP_ADMIN_SORTIES_ADMIN]
                items:
                    - app.admin.sorties
            app.admin.group.principal.ateliers:
                on_top: true
                label: "Ateliers"
                icon: '<i class="fa fa-pencil"></i>'
                roles: [ROLE_APP_ADMIN_ATELIERS_GUEST, ROLE_APP_ADMIN_ATELIERS_STAFF, ROLE_APP_ADMIN_ATELIERS_EDITOR, ROLE_APP_ADMIN_ATELIERS_ADMIN]
                items:
                    - app.admin.ateliers
            app.admin.group.principal.cours:
                on_top: true
                label: "Cours"
                icon: '<i class="fa fa-book"></i>'
                roles: [ROLE_APP_ADMIN_COURS_GUEST, ROLE_APP_ADMIN_COURS_STAFF, ROLE_APP_ADMIN_COURS_EDITOR, ROLE_APP_ADMIN_COURS_ADMIN]
                items:
                    - app.admin.cours
            app.admin.group.principal.partenaires:
                on_top: true
                label: "Partenaires"
                icon: '<i class="fa fa-user-secret"></i>'
                roles: [ROLE_APP_ADMIN_PARTENAIRES_GUEST, ROLE_APP_ADMIN_PARTENAIRES_STAFF, ROLE_APP_ADMIN_PARTENAIRES_EDITOR, ROLE_APP_ADMIN_PARTENAIRES_ADMIN]
                items:
                    - app.admin.partenaires
            app.admin.group.principal.blog:
                on_top: true
                label: "Blog"
                icon: '<i class="fa fa-rss"></i>'
                roles: [ROLE_APP_ADMIN_BLOG_GUEST, ROLE_APP_ADMIN_BLOG_STAFF, ROLE_APP_ADMIN_BLOG_EDITOR, ROLE_APP_ADMIN_BLOG_ADMIN]
                items:
                    - app.admin.blog
            app.admin.group.principal.tags:
                on_top: true
                label: "Tags"
                icon: '<i class="fa fa-tags"></i>'
                roles: [ROLE_APP_ADMIN_TAGS_GUEST, ROLE_APP_ADMIN_TAGS_STAFF, ROLE_APP_ADMIN_TAGS_EDITOR, ROLE_APP_ADMIN_TAGS_ADMIN]
                items:
                    - app.admin.tags
            app.admin.group.principal.medias:
                on_top: true
                label: "Medias"
                icon: '<i class="fa fa-th"></i>'
                roles: [ROLE_SONATA_MEDIA_ADMIN_MEDIA_EDITOR, ROLE_SONATA_MEDIA_ADMIN_MEDIA_STAFF, ROLE_SONATA_MEDIA_ADMIN_MEDIA_GUEST, ROLE_SONATA_MEDIA_ADMIN_MEDIA_ADMIN]
                items:
                    - sonata.media.admin.media
            app.admin.group.principal.demandenewsletter:
                on_top: true
                label: "Demande Newsletter"
                icon: '<i class="fa fa-envelope-o"></i>'
                roles: [ROLE_APP_ADMIN_NEWSLETTER_GUEST, ROLE_APP_ADMIN_NEWSLETTER_STAFF, ROLE_APP_ADMIN_NEWSLETTER_EDITOR, ROLE_APP_ADMIN_NEWSLETTER_ADMIN]
                items:
                    - app.admin.newsletter
            app.admin.group.principal.demandeacces:
                on_top: true
                label: "Demande d'acces"
                icon: '<i class="glyphicon glyphicon-log-in"></i>'
                roles: [ROLE_APP_ADMIN_ACCES_GUEST, ROLE_APP_ADMIN_ACCES_STAFF, ROLE_APP_ADMIN_ACCES_EDITOR, ROLE_APP_ADMIN_ACCES_ADMIN]
                items:
                    - app.admin.acces
            app.admin.group.principal.parametres:
                keep_open: false
                label: "Outils"
                icon: '<i class="fa fa-cogs"></i>'
                label_catalogue: AppBundle
                items:
                    - route: admin_parametre_list
                      roles: [ROLE_APP_ADMIN_PARAMETRES_GUEST, ROLE_APP_ADMIN_PARAMETRES_STAFF, ROLE_APP_ADMIN_PARAMETRES_EDITOR, ROLE_APP_ADMIN_PARAMETRES_ADMIN]
                      label: "Parametres du site"
                    - route: admin_conge_list
                      roles: [ROLE_APP_ADMIN_CONGES_GUEST, ROLE_APP_ADMIN_CONGES_STAFF, ROLE_APP_ADMIN_CONGES_EDITOR, ROLE_APP_ADMIN_CONGES_ADMIN]
                      label: "Vacances et jours fériés"
            app.admin.group.principal.users:
                keep_open: false
                label: "Utilisateurs"
                label_catalogue: AppBundle
                icon: '<i class="fa fa-users"></i>'
                items:
                    - route: admin_utilisateur_list
                      roles: [ROLE_SONATA_USER_ADMIN_USER_EDITOR, ROLE_SONATA_USER_ADMIN_USER_STAFF, ROLE_SONATA_USER_ADMIN_USER_GUEST, ROLE_SONATA_USER_ADMIN_USER_ADMIN]
                      label: "Utilisateurs"
                    - route: admin_utilisateur_droits_list
                      roles: [ROLE_SONATA_USER_ADMIN_GROUP_EDITOR, ROLE_SONATA_USER_ADMIN_GROUP_STAFF, ROLE_SONATA_USER_ADMIN_GROUP_GUEST, ROLE_SONATA_USER_ADMIN_GROUP_ADMIN]
                      label: "Groupes"
                    - route: admin_import_list
                      roles: [ROLE_APP_ADMIN_IMPORTS_GUEST, ROLE_APP_ADMIN_IMPORTS_STAFF, ROLE_APP_ADMIN_IMPORTS_EDITOR, ROLE_APP_ADMIN_IMPORTS_ADMIN]
                      label: "Imports"
        blocks:
            -
                class: col-lg-2 col-xs-6
                position: top
                type: app.admin.block.stats
                settings:
                    template: :AdminCustom/dashboard:block/block_stats.html.twig
                    icon: fa-users
                    text: Utilisateurs
                    color: bg-green
                    entity: AppBundle\Entity\Utilisateur
                    filters:
            -
                class: col-lg-2 col-xs-6
                position: top
                type: app.admin.block.stats
                settings:
                    template: :AdminCustom/dashboard:block/block_stats.html.twig
                    icon: fa-calendar
                    text: Evenements
                    color: bg-aqua
                    entity: AppBundle\Entity\Evenement
                    filters:
            -
                class: col-lg-2 col-xs-6
                position: top
                type: app.admin.block.stats
                settings:
                    template: :AdminCustom/dashboard:block/block_stats.html.twig
                    icon: fa-clock-o
                    text: Kouryukai
                    color: bg-olive
                    entity: AppBundle\Entity\Kouryukai
                    filters:
            -
                class: col-lg-2 col-xs-6
                position: top
                type: app.admin.block.stats
                settings:
                    template: :AdminCustom/dashboard:block/block_stats.html.twig
                    icon: fa-car
                    text: Sorties
                    color: bg-yellow
                    entity: AppBundle\Entity\Sortie
                    filters:
            -
                class: col-lg-2 col-xs-6
                position: top
                type: app.admin.block.stats
                settings:
                    template: :AdminCustom/dashboard:block/block_stats.html.twig
                    icon: fa-pencil
                    text: Ateliers
                    color: bg-maroon
                    entity: AppBundle\Entity\Atelier
                    filters:
            -
                class: col-lg-2 col-xs-6
                position: top
                type: app.admin.block.stats
                settings:
                    template: :AdminCustom/dashboard:block/block_stats.html.twig
                    icon: fa-user-secret
                    text: Partenaires
                    color: bg-teal
                    entity: AppBundle\Entity\Partenaire
                    filters:
            -
                class: col-lg-12 col-xs-12
                position: top
                type: app.admin.block.statistique
                settings:
                    template: :AdminCustom/dashboard:block/statistique.html.twig
                    icon:  fa-clock-o
                    color: bg-white
                    filters:
            -
                class: col-lg-12 col-xs-12
                position: top
                type: app.admin.block.timeline
                settings:
                    template: :AdminCustom/dashboard:block/timeline.html.twig
                    icon:  fa-clock-o
                    color: bg-white
                    filters: