sonata_admin:
    title: 'Rouen Japon Administration'
    title_logo: medias/favicons/favicon-32x32.png
    options:
        html5_validate: true
        # Auto order groups and admins by label or id
        sort_admins: false
        confirm_exit: true # prevent data corruption when multiple users edit an object at the same tim
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]

        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]

        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
        layout: :AdminCustom:/template/standard_layout.html.twig
        edit:   :AdminCustom:/template/edit.html.twig
    dashboard:
        groups:
            app.admin.group.principal.evenements:
                on_top: true
                label: "Evenements"
                icon: '<i class="fa fa-calendar"></i>'
                roles: [ROLE_APP_ADMIN_EVENEMENTS_ADMIN]
                items:
                    - app.admin.evenements
            app.admin.group.principal.actualites:
                on_top: true
                label: "Actualites"
                icon: '<i class="fa fa-newspaper-o"></i>'
                roles: [ROLE_APP_ADMIN_ACTUALITES_ADMIN]
                items:
                    - app.admin.actualites
            app.admin.group.principal.sorties:
                on_top: true
                label: "Sorties"
                icon: '<i class="fa fa-random"></i>'
                roles: [ROLE_APP_ADMIN_SORTIES_ADMIN]
                items:
                    - app.admin.sorties
            app.admin.group.principal.ateliers:
                on_top: true
                label: "Ateliers"
                icon: '<i class="fa fa-pencil"></i>'
                roles: [ROLE_APP_ADMIN_ATELIERS_ADMIN]
                items:
                    - app.admin.ateliers
            app.admin.group.principal.cours:
                on_top: true
                label: "Cours"
                icon: '<i class="fa fa-book"></i>'
                roles: [ROLE_APP_ADMIN_COURS_ADMIN]
                items:
                    - app.admin.cours
            app.admin.group.principal.parametres:
                on_top: true
                label: "Parametres"
                icon: '<i class="fa fa-cogs"></i>'
                roles: [ROLE_APP_ADMIN_PARAMETRES_ADMIN]
                items:
                    - app.admin.parametres
            app.admin.group.principal.users:
                keep_open: false
                label: "Utilisateurs"
                label_catalogue: AppBundle
                icon: '<i class="fa fa-users"></i>'
                items:
                    - route: admin_utilisateur_list
                      roles: [ROLE_SONATA_USER_ADMIN_USER_ADMIN]
                      label: "Utilisateurs"
                    - route: admin_utilisateur_droits_list
                      roles: [ROLE_SONATA_USER_ADMIN_GROUP_ADMIN]
                      label: "Groupes"
        blocks:
            -
                class: col-lg-3 col-xs-6
                position: top
                type: app.admin.block.stats
                settings:
                    template: SonataAdminBundle:Block:block_stats.html.twig
                    icon:  fa-users
                    text:  Utilisateurs
                    color: bg-green
                    entity: AppBundle\Entity\Utilisateur
                    filters:
            -
                class: col-lg-3 col-xs-6
                position: top
                type: app.admin.block.stats
                settings:
                    template: SonataAdminBundle:Block:block_stats.html.twig
                    icon:  fa-calendar
                    text:  Evenements
                    color: bg-aqua
                    entity: AppBundle\Entity\Evenement
                    filters:
            -
                class: col-lg-3 col-xs-6
                position: top
                type: app.admin.block.stats
                settings:
                    template: SonataAdminBundle:Block:block_stats.html.twig
                    icon:  fa-car
                    text:  Sorties
                    color: bg-yellow
                    entity: AppBundle\Entity\Sortie
                    filters:
            -
                class: col-lg-3 col-xs-6
                position: top
                type: app.admin.block.stats
                settings:
                    template: SonataAdminBundle:Block:block_stats.html.twig
                    icon:  fa-graduation-cap
                    text:  Ateliers
                    color: bg-maroon
                    entity: AppBundle\Entity\Atelier
                    filters:
            -
                class: col-lg-12 col-xs-12
                position: top
                type: app.admin.block.timeline
                settings:
                    template: :AdminCustom/dashboard:block/timeline.html.twig
                    icon:  fa-clock-o
                    color: bg-white
                    filters: