<?php

namespace Application\Sonata\NewsBundle\Entity;

use Sonata\NewsBundle\Entity\BasePostRepository;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en#querying:custom-repositories
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/query-builder/en
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/dql-doctrine-query-language/en
 */
class PostRepository extends BasePostRepository
{
    public function findAllValidOverOneMonth($admin = false)
    {
        if ($admin) {
            $query = $this
                ->getEntityManager()
                ->createQuery('SELECT e '
                    . 'FROM ApplicationSonataNewsBundle:Post e '
                    . 'WHERE e.createdAt >= :dateFin '
                    . 'ORDER BY e.publicationDateStart DESC')
                ->setParameter('dateFin', date("Y-m-d",strtotime("-1 month")));
        } else {
            $query = $this
                ->getEntityManager()
                ->createQuery('SELECT e '
                    . 'FROM ApplicationSonataNewsBundle:Post e '
                    . 'WHERE e.enabled = :affiche '
                    . 'AND e.publicationDateStart <= :datePublication '
                    . 'AND e.createdAt >= :dateFin '
                    . 'ORDER BY e.publicationDateStart DESC')
                ->setParameters([
                    'affiche' => true,
                    'datePublication' => date("Y-m-d"),
                    'dateFin' => date("Y-m-d",strtotime("-1 month"))
                ]);
        }
        return $query->getResult();
    }

    public function getTop($limit)
    {
        return $this
            ->getEntityManager()
            ->createQuery('SELECT e '
                . 'FROM ApplicationSonataNewsBundle:Post e '
                . 'WHERE e.enabled = :affiche '
                . 'AND e.publicationDateStart <= :datePublication '
                . 'ORDER BY e.createdAt DESC')
            ->setParameters([
                'affiche' => true,
                'datePublication' => date("Y-m-d")
            ])
            ->setMaxResults($limit)
            ->getResult();
    }
}
